name: Build and push images on tags

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_and_push:
    name: ${{ matrix.app.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.gitRef }}
      - name: Build and Push Tagged Image
        uses: /home/runner/work/ckanext-datagovuk/ckanext-datagovuk/.github/workflows/build-image.yaml
        with:
          buildType: build_push_ckan
          gitRef: ${{ github.ref_name }}
